PUT http://localhost:3000/api/blogs/9i0j1k2l
Content-Type: application/json

// la propiedad tambien va entre comillas
{
    "titulo": "Nuevo titulo para el blog de prueba",
    "contenido": "Este es el contenido nuevo del blog de prueba.",
    "autor": "Autor Anónimo"
}